[[redirects]]
  from = "/api/*"
  to = "https://6481c335b16c621fe9ec50fe--golden-basbousa-98d7c5.netlify.app/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/client/index.html"
  status = 200